### ISSUE TITLE
динамические сайдбары

### ISSUE THREAD

**Issue by nevigen** [AlekVolsk/master3#10]
вопрос в динамичности сайдбаров.
если модулей в них нет или они пустые, место под сайбра остается всегда.

**Comment by AlekVolsk** [comment]
не могу подтвердить баг
без сайдбаров http://prntscr.com/lm7zvy
только A http://prntscr.com/lm80fc
только B http://prntscr.com/lm80oj
A+B http://prntscr.com/lm80xe
A+B, оба слева http://prntscr.com/lm819q
A+B, оба справа http://prntscr.com/lm81m4

**Comment by AlekVolsk** [comment]
возможно, просто речь идет о модулях, которые опубликованы, но не рендерят контент по причине внутренних условий, но это уже не от шаблона зависит
