### ISSUE TITLE
отсутствует или не подключается

### ISSUE THREAD

**Issue by nevigen** [AlekVolsk/master3#2]
нет файла uikit.min.css
/templates/master3/uikit/css/uikit.min.css
как собственно и uikit.css
и путь не верен !
/uikit/ лишнее

**Comment by nevigen** [comment]
логичнее тогда сделать папку 
уикит чтобы туда загрдуать просто апдейт самого уикита как есть а в верхних папках ЖС и ЦСС размеcтить custom.css theme.css и подключать тогда все скрипты кторые находятся в JS папке шаблона.

**Comment by AlekVolsk** [comment]
папка uikit - это по сути папка всего фрейма юикита, который можно в шабе обновлять целиком либо полностью вырезать, если используется своя компилируемая сборка

папка присутствует, но забыл прописать в templateDetails, исправлено
