### ISSUE TITLE
поиск

### ISSUE THREAD

**Issue by nevigen** [AlekVolsk/master3#3]
модуль поиска сделать с кликабельной иконкой
https://getuikit.com/docs/form#clickable-icons

**Comment by nevigen** [comment]
и может сделать позицию отдельную под поиск в шаблоне..

**Comment by AlekVolsk** [comment]
> модуль поиска сделать с кликабельной иконкой
кнопка кликабельна https://github.com/AlekVolsk/master3/blob/master/html/mod_search/default.php#L24

> и может сделать позицию отдельную под поиск в шаблоне
есть позиции в тулбаре, в шапке, в навбаре - этого более чем достаточно
